<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '3577762457340114e0b64892355e11ba6ec110a6',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '3577762457340114e0b64892355e11ba6ec110a6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'archtechx/enums' => array(
            'pretty_version' => 'v1.1.0',
            'version' => '1.1.0.0',
            'reference' => '37326d5e26cdfcc2810f4664cdd625ea4fd528d7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../archtechx/enums',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'bacon/bacon-qr-code' => array(
            'pretty_version' => '2.0.8',
            'version' => '2.0.8.0',
            'reference' => '8674e51bb65af933a5ffaf1c308a660387c35c22',
            'type' => 'library',
            'install_path' => __DIR__ . '/../bacon/bacon-qr-code',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'carbonphp/carbon-doctrine-types' => array(
            'pretty_version' => '3.2.0',
            'version' => '3.2.0.0',
            'reference' => '18ba5ddfec8976260ead6e866180bd5d2f71aa1d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../carbonphp/carbon-doctrine-types',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/semver' => array(
            'pretty_version' => '3.4.3',
            'version' => '3.4.3.0',
            'reference' => '4313d26ada5e0c4edfbd1dc481a92ff7bff91f12',
            'type' => 'library',
            'install_path' => __DIR__ . '/./semver',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'dasprid/enum' => array(
            'pretty_version' => '1.0.6',
            'version' => '1.0.6.0',
            'reference' => '8dfd07c6d2cf31c8da90c53b83c026c7696dda90',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dasprid/enum',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dflydev/dot-access-data' => array(
            'pretty_version' => 'v3.0.3',
            'version' => '3.0.3.0',
            'reference' => 'a23a2bf4f31d3518f3ecb38660c95715dfead60f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dflydev/dot-access-data',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'doctrine/inflector' => array(
            'pretty_version' => '2.0.10',
            'version' => '2.0.10.0',
            'reference' => '5817d0659c5b50c9b950feb9af7b9668e2c436bc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/inflector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dragon-code/contracts' => array(
            'pretty_version' => '2.23.0',
            'version' => '2.23.0.0',
            'reference' => '44dbad923f152e0dc2699fbac2d33b65dd6a8f7d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dragon-code/contracts',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'dragon-code/pretty-array' => array(
            'pretty_version' => 'v4.1.0',
            'version' => '4.1.0.0',
            'reference' => '6c84e2454491b414efbd37985c322712cdf9012f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dragon-code/pretty-array',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'dragon-code/support' => array(
            'pretty_version' => '6.15.0',
            'version' => '6.15.0.0',
            'reference' => '087d7baaa963cdbb24e901dc27e10cdc31c2529c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dragon-code/support',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'endroid/qr-code' => array(
            'pretty_version' => '5.0.7',
            'version' => '5.0.7.0',
            'reference' => '0cc00f0626b73bc71a1ea17af01387d0ac75e046',
            'type' => 'library',
            'install_path' => __DIR__ . '/../endroid/qr-code',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/bus' => array(
            'pretty_version' => 'v10.48.25',
            'version' => '10.48.25.0',
            'reference' => 'c66d57011eec385055e1426d026c270aeecb05aa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/bus',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/collections' => array(
            'pretty_version' => 'v10.48.25',
            'version' => '10.48.25.0',
            'reference' => '48de3d6bc6aa779112ddcb608a3a96fc975d89d8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/collections',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/conditionable' => array(
            'pretty_version' => 'v10.48.25',
            'version' => '10.48.25.0',
            'reference' => '3ee34ac306fafc2a6f19cd7cd68c9af389e432a5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/conditionable',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/config' => array(
            'pretty_version' => 'v10.48.25',
            'version' => '10.48.25.0',
            'reference' => 'd5e83ceff5c4d5607b1b81763eb4c436911c35da',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/config',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'illuminate/console' => array(
            'pretty_version' => 'v10.48.25',
            'version' => '10.48.25.0',
            'reference' => 'd10e2fb5331b82b2e58a9be05ea798e5a0899890',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/console',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/container' => array(
            'pretty_version' => 'v10.48.25',
            'version' => '10.48.25.0',
            'reference' => 'ed6253f7dd3a67d468b2cc7a69a657e1f14c7ba3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/contracts' => array(
            'pretty_version' => 'v10.48.25',
            'version' => '10.48.25.0',
            'reference' => 'f90663a69f926105a70b78060a31f3c64e2d1c74',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/events' => array(
            'pretty_version' => 'v10.48.25',
            'version' => '10.48.25.0',
            'reference' => '3edcdad2f2fe6da6802afb0a256b0f7ee00d72e9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/events',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/filesystem' => array(
            'pretty_version' => 'v10.48.25',
            'version' => '10.48.25.0',
            'reference' => '592fb581a52fba43bf78c2e4b22db540c9f9f149',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/filesystem',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/macroable' => array(
            'pretty_version' => 'v10.48.25',
            'version' => '10.48.25.0',
            'reference' => 'dff667a46ac37b634dcf68909d9d41e94dc97c27',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/macroable',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/pipeline' => array(
            'pretty_version' => 'v10.48.25',
            'version' => '10.48.25.0',
            'reference' => '3030a131e5e9cb18c9a826428fcffc076df9dcd7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/pipeline',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/support' => array(
            'pretty_version' => 'v10.48.25',
            'version' => '10.48.25.0',
            'reference' => '64b258f80175c658aef9e22dd3f2ba18c99b243c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/support',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/view' => array(
            'pretty_version' => 'v10.48.25',
            'version' => '10.48.25.0',
            'reference' => '51c9feaf1364bc35ffb056463cde1d6e639b7c6e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/view',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laravel-lang/config' => array(
            'pretty_version' => '1.10.0',
            'version' => '1.10.0.0',
            'reference' => '67c9273a2e5487441a7034c2422bb1527200bce5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel-lang/config',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'laravel-lang/lang' => array(
            'pretty_version' => '14.8.0',
            'version' => '14.8.0.0',
            'reference' => '7318bd6dc8299d62fcee1109489bfb0ec82d1e25',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel-lang/lang',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'laravel-lang/locale-list' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'reference' => '48b8e4304f8b1ad34456270d35d44ca0c3e6ea0d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel-lang/locale-list',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'laravel-lang/locales' => array(
            'pretty_version' => '2.9.2',
            'version' => '2.9.2.0',
            'reference' => 'e7914ccfb91432ebebacf46697b573a330d702c7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel-lang/locales',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'laravel-lang/native-country-names' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'reference' => 'cddca6627c8732770a2e2c11c921753b6d0adb66',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel-lang/native-country-names',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'laravel-lang/native-currency-names' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'reference' => '2e0fbe039421ac753b4fd5256bd239147a0a88fe',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel-lang/native-currency-names',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'laravel-lang/native-locale-names' => array(
            'pretty_version' => '2.3.0',
            'version' => '2.3.0.0',
            'reference' => '39ef3330938b74277456049bf386453109e4d05c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel-lang/native-locale-names',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'laravel-lang/publisher' => array(
            'pretty_version' => '16.4.0',
            'version' => '16.4.0.0',
            'reference' => '7812e7a07e6f2fdb7d258f3ab1d481d1cbf7f32c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel-lang/publisher',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'laravel/fortify' => array(
            'pretty_version' => 'v1.21.1',
            'version' => '1.21.1.0',
            'reference' => '405388fd399264715573e23ed2f368fbce426da3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/fortify',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laravel/jetstream' => array(
            'pretty_version' => 'v4.3.1',
            'version' => '4.3.1.0',
            'reference' => '1cb2b30664d818491b3193ccbdd97758fa5b60fc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/jetstream',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laravel/prompts' => array(
            'pretty_version' => 'v0.1.25',
            'version' => '0.1.25.0',
            'reference' => '7b4029a84c37cb2725fc7f011586e2997040bc95',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/prompts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/commonmark' => array(
            'pretty_version' => '2.5.3',
            'version' => '2.5.3.0',
            'reference' => 'b650144166dfa7703e62a22e493b853b58d874b0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/commonmark',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'league/config' => array(
            'pretty_version' => 'v1.2.0',
            'version' => '1.2.0.0',
            'reference' => '754b3604fb2984c71f4af4a9cbe7b57f346ec1f3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/config',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'mobiledetect/mobiledetectlib' => array(
            'pretty_version' => '4.8.06',
            'version' => '4.8.06.0',
            'reference' => 'af088b54cecc13b3264edca7da93a89ba7aa2d9e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mobiledetect/mobiledetectlib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nesbot/carbon' => array(
            'pretty_version' => '2.72.5',
            'version' => '2.72.5.0',
            'reference' => 'afd46589c216118ecd48ff2b95d77596af1e57ed',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nesbot/carbon',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nette/schema' => array(
            'pretty_version' => 'v1.3.2',
            'version' => '1.3.2.0',
            'reference' => 'da801d52f0354f70a638673c4a0f04e16529431d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nette/schema',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'nette/utils' => array(
            'pretty_version' => 'v4.0.5',
            'version' => '4.0.5.0',
            'reference' => '736c567e257dbe0fcf6ce81b4d6dbe05c6899f96',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nette/utils',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'nunomaduro/termwind' => array(
            'pretty_version' => 'v1.17.0',
            'version' => '1.17.0.0',
            'reference' => '5369ef84d8142c1d87e4ec278711d4ece3cbf301',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nunomaduro/termwind',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paragonie/constant_time_encoding' => array(
            'pretty_version' => 'v3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'df1e7fde177501eee2037dd159cf04f5f301a512',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/constant_time_encoding',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pragmarx/google2fa' => array(
            'pretty_version' => 'v8.0.3',
            'version' => '8.0.3.0',
            'reference' => '6f8d87ebd5afbf7790bde1ffc7579c7c705e0fad',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pragmarx/google2fa',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/clock' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'e41a24703d4560fd0acb709162f73b8adfc3aa0d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/clock',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/clock-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/container' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'c71ecc56dfe541dbd90c5360474fbc405f8d5963',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.1|2.0',
            ),
        ),
        'psr/event-dispatcher' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'dbefd12671e8a14ec7f180cab83036ed26714bb0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'psr/event-dispatcher-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '2.0',
            'version' => '2.0.0.0',
            'reference' => '402d35bcb92c70c026d1a6a9883f06b2ead23d71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'psr/log' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => 'f16e1d5863e37f8d8c2a01719f5b34baa2b714d3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0|3.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '764e0b3939f5ca87cb904f570ef9be2d78a07865',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'simplesoftwareio/simple-qrcode' => array(
            'pretty_version' => '4.2.0',
            'version' => '4.2.0.0',
            'reference' => '916db7948ca6772d54bb617259c768c9cdc8d537',
            'type' => 'library',
            'install_path' => __DIR__ . '/../simplesoftwareio/simple-qrcode',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v6.4.15',
            'version' => '6.4.15.0',
            'reference' => 'f1fc6f47283e27336e7cebb9e8946c8de7bff9bd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v3.5.1',
            'version' => '3.5.1.0',
            'reference' => '74c71c939a79f7d5bf3c1ce9f5ea37ba0114c6f6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/error-handler' => array(
            'pretty_version' => 'v7.2.0',
            'version' => '7.2.0.0',
            'reference' => '672b3dd1ef8b87119b446d67c58c106c43f965fe',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/error-handler',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => 'v7.2.0',
            'version' => '7.2.0.0',
            'reference' => '910c5db85a5356d0fea57680defec4e99eb9c8c1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/event-dispatcher-contracts' => array(
            'pretty_version' => 'v3.5.1',
            'version' => '3.5.1.0',
            'reference' => '7642f5e970b672283b7823222ae8ef8bbc160b9f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher-contracts',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/event-dispatcher-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '2.0|3.0',
            ),
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v6.4.13',
            'version' => '6.4.13.0',
            'reference' => 'daea9eca0b08d0ed1dc9ab702a46128fd1be4958',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-foundation' => array(
            'pretty_version' => 'v7.2.0',
            'version' => '7.2.0.0',
            'reference' => 'e88a66c3997859532bc2ddd6dd8f35aba2711744',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-foundation',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/http-kernel' => array(
            'pretty_version' => 'v7.2.0',
            'version' => '7.2.0.0',
            'reference' => '6b4722a25e0aed1ccb4914b9bcbd493cc4676b4d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-kernel',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.31.0',
            'version' => '1.31.0.0',
            'reference' => 'a3cc8b044a6ea513310cbd48ef7333b384945638',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'pretty_version' => 'v1.31.0',
            'version' => '1.31.0.0',
            'reference' => 'b9123926e3b7bc2f98c02ad54f6a4b02b91a8abe',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-grapheme',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.31.0',
            'version' => '1.31.0.0',
            'reference' => '3833d7255cc303546435cb650316bff708a1c75c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.31.0',
            'version' => '1.31.0.0',
            'reference' => '85181ba99b2345b0ef10ce42ecac37612d9fd341',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.31.0',
            'version' => '1.31.0.0',
            'reference' => '60328e362d4c2c802a54fcbf04f9d3fb892b4cf8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php81' => array(
            'pretty_version' => 'v1.31.0',
            'version' => '1.31.0.0',
            'reference' => '4a4cfc2d253c21a5ad0e53071df248ed48c6ce5c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php81',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/polyfill-php83' => array(
            'pretty_version' => 'v1.31.0',
            'version' => '1.31.0.0',
            'reference' => '2fb86d65e2d424369ad2905e83b236a8805ba491',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php83',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v6.4.15',
            'version' => '6.4.15.0',
            'reference' => '3cb242f059c14ae08591c5c4087d1fe443564392',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v3.5.1',
            'version' => '3.5.1.0',
            'reference' => 'e53260aabf78fb3d63f8d79d69ece59f80d5eda0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/string' => array(
            'pretty_version' => 'v7.2.0',
            'version' => '7.2.0.0',
            'reference' => '446e0d146f991dde3e73f45f2c97a9faad773c82',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/string',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation' => array(
            'pretty_version' => 'v6.4.13',
            'version' => '6.4.13.0',
            'reference' => 'bee9bfabfa8b4045a66bf82520e492cddbaffa66',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation-contracts' => array(
            'pretty_version' => 'v3.5.1',
            'version' => '3.5.1.0',
            'reference' => '4667ff3bd513750603a09c8dedbea942487fb07c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.3|3.0',
            ),
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => 'v7.2.0',
            'version' => '7.2.0.0',
            'reference' => 'c6a22929407dec8765d6e2b6ff85b800b245879c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'voku/portable-ascii' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => 'b1d923f88091c6bf09699efcd7c8a1b1bfd7351d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../voku/portable-ascii',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
